import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'bg-elevated-dark': '#22263A',
        tertiary: '#ffb695',
        'on-primary-fixed-variant': '#3323cc',
        'primary-fixed-dim': '#c3c0ff',
        'bg-base-dark': '#0F1117',
        'on-primary-container': '#ffffff',
        'on-secondary-fixed-variant': '#004c6e',
        'outline-variant': '#e5e7eb',
        warning: '#F59E0B',
        'on-primary-fixed': '#0f0069',
        'tertiary-fixed': '#ffdbcc',
        'on-surface': '#111827',
        'secondary-fixed': '#c9e6ff',
        'tertiary-fixed-dim': '#ffb695',
        'bg-overlay-dark': '#2D3148',
        'inverse-on-surface': '#ffffff',
        'on-error-container': '#ffdad6',
        'bg-surface-dark': '#1A1D27',
        'border-light': '#E2E8F0',
        'on-tertiary-container': '#4a332d',
        secondary: '#0ea5e9',
        outline: '#9ca3af',
        'surface-container': '#ffffff',
        'primary-light': '#6366F1',
        'on-tertiary': '#571f00',
        error: '#ef4444',
        'secondary-fixed-dim': '#89ceff',
        'secondary-container': '#e0f2fe',
        'surface-container-highest': '#f3f4f6',
        'on-secondary-fixed': '#001e2f',
        'bg-surface-light': '#FFFFFF',
        'on-tertiary-fixed-variant': '#7b2f00',
        'on-error': '#ffffff',
        primary: '#4f46e5',
        'on-surface-variant': '#4b5563',
        'on-background': '#111827',
        'error-container': '#fee2e2',
        'bg-overlay-light': '#F1F3F9',
        'inverse-surface': '#111827',
        surface: '#f8f9fa',
        'bg-base-light': '#F8F9FC',
        'on-secondary-container': '#075985',
        'surface-container-high': '#f9fafb',
        'surface-tint': '#4f46e5',
        'surface-container-low': '#f3f4f5',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#351000',
        info: '#3B82F6',
        success: '#10B981',
        'primary-fixed': '#e2dfff',
        'primary-container': '#4f46e5',
        danger: '#EF4444',
        'surface-container-lowest': '#ffffff',
        'border-dark': '#2E3250',
        'tertiary-container': '#ffdbcc',
        background: '#f8f9fa',
        'primary-dark': '#3730A3',
        'surface-variant': '#f3f4f6',
        'inverse-primary': '#4d44e3',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        12: '48px',
        16: '64px',
        gutter: '16px',
        'topbar-height': '60px',
        'sidebar-expanded': '184px',
        'sidebar-collapsed': '64px',
      },
      fontFamily: {
        label: ['Inter', 'sans-serif'],
        h2: ['Noto Sans KR', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        h1: ['Noto Sans KR', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        h3: ['Noto Sans KR', 'sans-serif'],
        display: ['Noto Sans KR', 'sans-serif'],
      },
      fontSize: {
        label: [
          '11px',
          { lineHeight: '1.3', letterSpacing: '0.04em', fontWeight: '500' },
        ],
        h2: ['16px', { lineHeight: '1.35', fontWeight: '600' }],
        body: ['13px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-lg': ['14px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        h1: ['19px', { lineHeight: '1.3', fontWeight: '700' }],
        caption: ['11px', { lineHeight: '1.4', fontWeight: '400' }],
        h3: ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        display: ['23px', { lineHeight: '1.2', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms],
}
